- name: Install Docker
  yum:
    name: docker
    state: installed
  when: ansible_os_family=="RedHat"

- name: Install Docker
  apt:
    name: docker.io
    state: present
  when: ansible_os_family=="Debian"

- name: Start docker   
  service:
    name: docker
    state: started
    # enabled: yes  
