---
# tasks file for http
- name: Install nginx
  yum:
    name: nginx
    state: installed

- name: Start nginx   
  service:
    name: nginx
    state: started
    # enabled: yes
  # notify: Firewall conf 

- name: Add firewall rules
  firewalld:
    port: "80/tcp"
    permanent: yes
    state: enabled
    immediate: yes 

- name: Create info.php
  template:
    src: info.php.j2
    dest: /usr/share/nginx/html/info.php
  notify: restart nginx    

- name: Php conf file
  template:
    src: php-fpm.conf.j2
    dest: /etc/nginx/conf.d/php-fpm.conf
  notify: restart nginx 