- name: User create playbook
  hosts: all
  become: yes
  tasks:

    - name: Create user1
      user:
        comment: "Just for test"
        name: "{{ user_name }}"
        state: present

    - name: Create directory
      file:
        path: /home/{{ user_name }}/.ssh/
        state: directory
        mode: 0700     
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Copy ssh public key
      copy:    
        src: files/id_rsa.pub
        dest: /home/{{ user_name }}/.ssh/id_rsa.pub
        backup: yes
        mode: 0644
        owner: "{{ user_name }}"
        group: "{{ user_name }}"